version: 2

models:
  - name: fact_teams
    description: "list of teams with coach, country data"
    columns:
      - name: team_name
        data_type: string
        description: ""

      - name: team_country
        data_type: string
        description: ""

      - name: home_stadium
        data_type: string
        description: ""

      - name: stadium_city
        data_type: string
        description: ""

      - name: capacity
        data_type: int64
        description: ""

      - name: full_name
        data_type: string
        description: ""

      - name: manager_nationality
        data_type: string
        description: ""

      - name: manager_dob
        data_type: timestamp
        description: ""

  - name: fact_matches
    description: >
      list of matches with goals, winner and attendance % 
    columns:
      - name: match_id
        data_type: string
        description: ""

      - name: season
        data_type: string
        description: ""

      - name: date_time
        data_type: timestamp
        description: ""

      - name: home_team
        data_type: string
        description: ""

      - name: away_team
        data_type: string
        description: ""

      - name: stadium
        data_type: string
        description: ""

      - name: home_team_score
        data_type: int64
        description: ""

      - name: away_team_score
        data_type: int64
        description: ""

      - name: winner
        data_type: string
        description: ""

      - name: penalty_shoot_out
        data_type: string
        description: ""

      - name: attendance
        data_type: int64
        description: ""

      - name: capacity
        data_type: int64
        description: ""

      - name: attendance_perc
        data_type: string
        description: ""

  - name: fact_goals
    description: >
      List of goals with full scoarer and assistent information 
    columns:
      - name: goal_id
        data_type: string
        description: ""

      - name: match_id
        data_type: string
        description: ""

      - name: pid
        data_type: string
        description: ""

      - name: time_of_goal
        data_type: string
        description: ""

      - name: goal_desc
        data_type: string
        description: ""

      - name: goal_scorer
        data_type: string
        description: ""

      - name: goal_nationality
        data_type: string
        description: ""

      - name: position
        data_type: string
        description: ""

      - name: height
        data_type: string
        description: ""

      - name: weight
        data_type: string
        description: ""

      - name: season
        data_type: string
        description: ""

      - name: assist
        data_type: string
        description: ""

      - name: assistent
        data_type: string
        description: ""

      - name: assistent_nationality
        data_type: string
        description: ""

      - name: assistent_position
        data_type: string
        description: ""

      - name: assistent_height
        data_type: string
        description: ""

      - name: assistent_weight
        data_type: string
        description: ""

      - name: date_time
        data_type: timestamp
        description: ""

      - name: home_team
        data_type: string
        description: ""

      - name: away_team
        data_type: string
        description: ""

      - name: stadium
        data_type: string
        description: ""
  